apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-deployment
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-deployment
  strategy: {}
  template:
    metadata:
      labels:
        app: nginx-deployment
    spec:
      containers:
      - image: nginx:1.19.2
        name: nginx
        resources:
          limits:
            cpu: "0.5"
            memory: 256Mi
          requests:
            cpu: "0.25"
            memory: 128Mi
        livenessProbe: # Aqui vamos definir a sonda de verificação de saúde.
          tcpSocket: # Vamos utilizar o protocolo TCP para a verificação.
            port: 80 # Vamos verificar a porta 80.
          initialDelaySeconds: 10 # Vamos esperar 10 segundos antes de executar a primeira verificação.
          periodSeconds: 10 # Vamos executar a verificação a cada 10 segundos.
          timeoutSeconds: 5 # Vamos esperar 5 segundos antes de considerar a verificação como falha.
          failureThreshold: 3 # Vamos considerar a sonda como falha após 3 tentativas.
