apiVersion: v1
kind: Pod
metadata:
  name: meu-pod-multicontainer
spec:
  containers:
  - name: nginx-container
    image: nginx
  - name: busybox-container
    image: busybox
    command: ['sh', '-c', 'echo Hello, world! && sleep infinity']
