apiVersion: v1
kind: Pod
metadata:
  name: meu-pod-multicontainer
spec:
  containers:
  - name: nginx-container
    image: nginx
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  - name: busybox-container
    image: busybox
    command: ['sh', '-c', 'echo Hello, world! && sleep infinity']
