apiVersion: v1
kind: PersistentVolume
metadata:
  name: meu-pv-nfs
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: <IP_DO_SERVIDOR_NFS>
    path: /caminho/para/compartilhamento/nfs
