apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: meu-pvc-nfs
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  volumeName: meu-pv-nfs
  resources:
    requests:
      storage: 5Gi
