name: Build and Deploy
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0
    - name: Install the dependencies
      run: |
        cd docs
        npm install
    - name: Build docs
      run: npx honkit build
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.USER_TOKEN }}
        BRANCH: gh-pages
        FOLDER: _book
